//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Snipper.rc

#define IDC_STATIC -1
#define IDC_CONTEXTMENU 101
#define IDI_MAINICON 102
#define IDD_SETTINGS_DLG 103

#define IDC_HOTKEY_COPY 1001
#define IDC_HOTKEY_SAVE 1002
#define IDC_HOTKEY_OCR  1003
#define IDC_HOTKEY_INTERACTIVE 1004
#define IDC_CHECK_STARTUP 1005
#define IDC_COMBO_LANGUAGE 1006

#define IDM_START_SNIP 40001
#define IDM_SETTINGS   40002
#define IDM_EXIT       40004

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

// String Table IDs
#define IDS_NOTIFY_COPY_SUCCESS      2001
#define IDS_NOTIFY_SAVE_SUCCESS      2002
#define IDS_NOTIFY_OCR_SUCCESS       2003
#define IDS_NOTIFY_OCR_SAVE_SUCCESS  2004
#define IDS_NOTIFY_OCR_NOTEXT        2005
#define IDS_NOTIFY_OCR_FAILED        2006

#define IDS_TOOLBAR_COPY_IMG         2010
#define IDS_TOOLBAR_SAVE_IMG         2011
#define IDS_TOOLBAR_COPY_OCR         2012
#define IDS_TOOLBAR_SAVE_OCR         2013

#define IDS_OVERLAY_MODE_COPY        2020
#define IDS_OVERLAY_MODE_SAVE        2021
#define IDS_OVERLAY_MODE_OCR         2022
#define IDS_OVERLAY_MODE_DEFAULT     2023
